.PHONY: documentation

# CHECK: python Issue11831

open_sw=firefox

# documentation:
# 	pydoc -w ../
# 	$(open_sw) src.html

open_html:
	#$(open_sw) ./html/src.html	
	firefox -new-window ./html/src.html